language: ruby
before_install: gem install bundler
bundler_args: --without yard guard metrics benchmarks
script: "bundle exec rake ci"
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - rbx-19mode
  - jruby-19mode
  - ruby-head
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
  email:
    recipients:
      - dan.kubb@gmail.com
    on_success: never
    on_failure: change
matrix:
  allow_failures:
    - rvm: ruby-head
  include:
    - rvm: jruby-19mode
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
    - rvm: jruby-head
      env: JRUBY_OPTS="$JRUBY_OPTS --debug"
